### ISSUE TITLE
consider using rollup

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-deploy#228]
in order to generate ESM bundles, it might be better to use https://rollupjs.org/ instead of webpack.

**Comment by trieloff** [comment]
Somewhat in favor of this. I think webpack is a beast that nobody is truly able to understand, and even in the team only you are willing to touch it at all. We are holding back on the latest webpack version anyway.

On the other hand, switching bundles has the potential to break things at scale.

On the third hand, this is the kind of breakage that our post-deploy tests are good at catching.

Maybe the best way would be to introduce this as a breaking change, so that we will pay extra attention to the upgrade.

**Comment by tripodsan** [comment]
> We are holding back on the latest webpack version anyway.

no, we're using 5.x. the config in the renovate.js is outdated.
