### ISSUE TITLE
Use the Fastly client library instead of fastly-native-promises

### ISSUE THREAD

**Issue by bosschaert** [adobe/helix-deploy#591]
To interact with Fastly Compute@Edge (deploy / update / etc) we currently use https://github.com/adobe/fastly-native-promises

Fastly publish their own client library: https://www.npmjs.com/package/fastly/

It would be better to use the provided library instead of our own.

**Comment by bosschaert** [comment]
I'd like to take a look at this. It might also contribute to fixing #587

**Comment by tripodsan** [comment]
I think @trieloff had some bad experience with the fastly js libraries - that's why we used our own.
if there is an issue, i'd rather fix fastly-native-promises. also it's quite large:

<img width="130" alt="image" src="https://github.com/adobe/helix-deploy/assets/917628/a2b6effe-a480-4b13-826f-bc31208d16c0">

and has a warning that it should not be used with c@e:

<img width="729" alt="image" src="https://github.com/adobe/helix-deploy/assets/917628/685a90fc-fb0e-42f6-a3e0-c4fcdb98b905">

**Comment by bosschaert** [comment]
Hi @tripodsan I did see that warning in NPM as well, but if you look here https://developer.fastly.com/reference/api/services/backend/ and click on the JavaScript tab of any of the APIs it's referenced there as part of the official Fastly documentation, so it's at least what Fastly seems to recommend there...

**Comment by trieloff** [comment]
No, that was my idea. I'd like to deprecate fastly-native-promises now that there is a maintained and supported client library from Fastly. I thought we could get it removed from the two biggest consumers (Hedy, and Admin) before we finally pull the plug.

**Comment by tripodsan** [comment]
I'm just concerned about the size 10mb!! I would not want to add this to the admin.

**Comment by bosschaert** [comment]
Closing this issue due to the size problem.
